### ISSUE TITLE
I can't start a party using the github.io link

### ISSUE THREAD

**Issue by bluesauce3** [dbilgili/PlayVi#1]
I just want to say this looks amazing and almost exactly what I am after, however I can't start a party using the link provided to the github.io page. I understand this hasn't been touched in years so may not work now. Do I have to host the app myself or something? (I'm unfamiliar with the Spotify API and understand really basic JS at most). In the Developer Tools console it did the 'server responded with an error of 404'. Sorry if this issue/question isn't relevant.
![image](https://github.com/dbilgili/PlayVi/assets/106856604/fad9c7c8-9afb-4e22-a32a-4a4ded568564)

**Comment by dbilgili** [comment]
There has been some changes on the server side, which have yet to be implemented into the frontend, hence the error I reckon. Currently there is no timeline for the implementation unfortunately, but once it's in place I will close this issue and then you will be notified 👍🏻
